### ISSUE TITLE
Example false positive situation

### ISSUE THREAD

**Issue by MyselfYangjz** [htrgouvea/zarn#41]
I use the sample code in https://heitorgouvea.me/2023/03/19/static-security-analysis-tool-perl, this should report output zero flaw is flawed
code：
#!/usr/bin/perl
 
use 5.018;
use strict;
use warnings;

sub main {
    my $name = "Zarn";
    
    system ("echo Hello World! $name");
}

exit main();

**Comment by htrgouvea** [comment]
Hi @MyselfYangjz, thanks for opening this issue.
I investigated and found the problem, in the next few days I will make a pull request for a solution.

**Comment by htrgouvea** [comment]
Hi @MyselfYangjz, 
I'm closing this issue, I made some updates. I believe the improvement will be significant.
In the future I will update some other things and improve the readability of the code.
Thanks a lot!
