### ISSUE TITLE
Is zarn.pl checking if the arguments on the command line are valid?

### ISSUE THREAD

**Issue by pierre-rouleau** [htrgouvea/zarn#52]
I just tried zarn and gave it the name of file that does not exists on --source and it did not even detect the error.

Something like:

```
>0@18:12:05 L1 rp@myTComp:[~/my/dvpub/perl-repos/zarn]  git:(main)zarn
zsh% perl zarn.pl --rules rules/default.yml --source file-does-not-exist.pm  --sarif report.sarif
>0@18:12:34 L1 rp@myTComp:[~/my/dvpub/perl-repos/zarn]  git:(main)zarn
zsh%   
```

The exit code is 0.  As if everything went just fine (my prompt always show the exit code of the last command).

Am I missing something?

**Comment by htrgouvea** [comment]
Hi @pierre-rouleau,
Thanks for your suggestion. I believe this PR: https://github.com/htrgouvea/zarn/pull/53 has the solution. Can you try Zarn one time more please?

**Comment by htrgouvea** [comment]
Hi, I'm closing this issue due to lack of responses. I believe the PR I made earlier resolved the issue. If there's anything else, let me know and we'll reopen this issue. Thanks.
